export const FilterActionTypes = {
  TOGGLE_FILTER_DROPDOWN: 'TOGGLE_FILTER_DROPDOWN',
  FILTER_ITEM: 'FILTER_ITEM',
  FETCH_LAUNCHES_BY_YEAR_START: 'FETCH_LAUNCHES_BY_YEAR_START',
  FETCH_LAUNCHES_BY_YEAR_SUCCESS: 'FETCH_LAUNCHES_BY_YEAR_SUCCESS',
  FETCH_LAUNCHES_BY_YEAR_FAILURE: 'FETCH_LAUNCHES_BY_YEAR_FAILURE'
}
