export const LaunchesActionTypes = {
  FETCH_LAUNCHES_START: 'FETCH_LAUNCHES_START',
  FETCH_LAUNCHES_SUCCESS: 'FETCH_LAUNCHES_SUCCESS',
  FETCH_LAUNCHES_FAILURE: 'FETCH_LAUNCHES_FAILURE',
  FILTER_LAUNCHES_BY_YEAR: 'FILTER_LAUNCHES_BY_YEAR',
  SORT_LAUNCHES: 'SORT_LAUNCHES'
}
